-- Security: email/phone verification, Google auth, account locking
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS email_verify_token TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS email_verify_expires TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone_number TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS phone_verify_code TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone_verify_expires TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS country_code VARCHAR(5) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS google_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(20) DEFAULT 'email',
  ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS login_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS country_code VARCHAR(5) DEFAULT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_google_id_idx ON users(google_id) WHERE google_id IS NOT NULL;

